version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./.secrets:/.secrets
    environment:
      DB_HOST: "db"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database-data:/var/lib/postgres/data
volumes:
  database-data:

